add database update function
ShmnK1ng/TMDB pull request #7
Opened 2023-08-03 12:46 UTC by ShmnK1ng

2023-08-22 09:11 UTC, vadzim-korzun-reed requested changes

2023-08-22 09:11 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/di/CoroutinesScopesModule.kt
> +        return CoroutineScope(SupervisorJob() + Dispatchers.Default)
Он нам не нужен

2023-08-22 09:11 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragmentViewModel.kt
> +            repository.getFlow()
repository.getFlow() это лишнее

2023-08-22 09:11 UTC, vadzim-korzun-reed commented on app/src/main/res/values/strings.xml
> +    <string name="init_database">init_database.db</string>
Такие стринги нужно в отдельный файлик стрингов выносить, что бы не включить их в локализацию

2023-08-22 09:11 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/repository/CategoriesRepositoryImpl.kt
> +    private val _categories: MutableStateFlow<List<Category>> = MutableStateFlow(listOf())
Тут через базу данных должно идти

2023-08-22 09:14 UTC, onreg requested changes

2023-08-22 09:14 UTC, onreg commented on app/src/main/java/com/example/tmdb/di/CoroutinesScopesModule.kt
> +        return CoroutineScope(SupervisorJob() + Dispatchers.Default)
Как то мне не очень нравится такой скоуп, по факту он не к чему не привязан.

2023-08-30 11:45 UTC, onreg requested changes

2023-08-30 11:45 UTC, onreg commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragmentViewModel.kt
>      }
2 скоупа

2023-08-30 11:45 UTC, onreg commented on app/src/main/java/com/example/tmdb/data/usecase/GetCategoriesUseCaseImpl.kt
> +    suspend fun getCategories(): Flow<List<Category>>
suspend

2023-08-30 11:45 UTC, onreg commented on app/src/main/java/com/example/tmdb/data/repository/CategoriesRepositoryImpl.kt
> +    suspend fun getCategories(): Flow<List<Category>>
suspend

2023-08-31 15:22 UTC, onreg approved these changes

2023-08-31 15:23 UTC, merged