add Movie overview viewing feature
ShmnK1ng/TMDB pull request #9
Opened 2023-10-20 15:18 UTC by ShmnK1ng

2023-10-23 16:37 UTC, vadzim-korzun-reed requested changes

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/Constants.kt
> +const val EMPTY_RELEASE_DATE = "Not specified"
Убрать

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/repository/MovieOverviewRepositoryImpl.kt
> +        return movieOverviewDao.getMovieWithGenresAndOverview(id).map {
Перенести в маппер

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/Movie.kt
> +) : java.io.Serializable
Parcelable

https://developer.android.com/kotlin/parcelize

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieDto.kt
> +    val type: Int = MOVIES_TYPE
Тип сделаеть enum и перенести в мапер

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieEntity.kt
> +    val type: Int
Добавить TypeConverter

https://developer.android.com/training/data-storage/room/referencing-data

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieOverview.kt
> +        )
форматирование

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieOverview.kt
> +    val id: Int = 0,
= 0

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieOverviewDto.kt
> +        )
форматирование

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/GenreEntity.kt
> +    val movie: MovieEntity,
удалить MovieEntity

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/GenreEntity.kt
> +    val movieId: Int,
привязать к MovieOverviewEntity

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieOverviewDao.kt
> +        val movieOverviewEntity = movieOverview.toMovieOverviewEntity()
упростить

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieOverviewDto.kt
> +    val releaseDate: String,
Instant

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MovieOverviewEntity.kt
> +    val releaseDate: String
Instant

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/MoviesDao.kt
> +                    updateMovieByRemoteIdAndType(movieEntity.remoteId, movieEntity.type, movieEntity.title, movieEntity.rating, movieEntity.posterPath)
Возможно не нужно

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/SeriesDto.kt
> +    val type: Int = SERIES_TYPE
удалить

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/model/SeriesOverviewDto.kt
> +    val releaseDate: String,
Instant

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/repository/MovieOverviewRepositoryImpl.kt
> +        if (previousJob?.isActive == false || previousJob == null) {
Избавиться от дублирования

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/data/usecase/GetMovieOverviewUseCaseImpl.kt
> +
пустая строчка

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/adapter/MovieItemAdapter.kt
> +        holder.itemView.setOnClickListener {
onBindViewHolder не должен содержать setOnClickListener

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragment.kt
> +    @SuppressLint("ResourceType")
@SuppressLint("ResourceType")

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragment.kt
>      override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
упросить

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragment.kt
> +                controller.navigate(R.id.movieOverviewFragment, args)
https://developer.android.com/guide/navigation/use-graph/pass-data

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragment.kt
> +            if (it != null) {
filterNotNull

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragment.kt
> +            Lifecycle.State.STARTED
Создать экстеншен

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragmentViewModel.kt
> +        viewModelScope.launch {
launch ненужен

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/HomeFragmentViewModel.kt
> +        viewModelScope.launch {
launch ненужен

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/MovieOverviewFragment.kt
> +                viewModel.viewCreated(args.getSerializable("movieItem") as Movie)
Передавать аргумент в конструктор

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/MovieOverviewFragment.kt
> +        viewModel.movieOverview.flowWithLifecycle(
в огтдельный метод

2023-10-23 16:37 UTC, vadzim-korzun-reed commented on app/src/main/java/com/example/tmdb/ui/home/MovieOverviewViewModel.kt
> +    val movieOverview: Flow<MovieOverview?> = _movieOverview.asStateFlow()
Индикатор закгрузки

2023-10-25 12:25 UTC, ShmnK1ng commented on app/src/main/java/com/example/tmdb/data/model/MoviesDao.kt
> +                    updateMovieByRemoteIdAndType(movieEntity.remoteId, movieEntity.type, movieEntity.title, movieEntity.rating, movieEntity.posterPath)
Нужно, мы проверяем есть ли этот муви в других категориях

2023-10-31 10:22 UTC, onreg requested changes

2023-10-31 10:22 UTC, onreg commented on app/build.gradle
> +        targetSdk 34
Зачем поднял `minSdk`?

2023-10-31 10:22 UTC, onreg commented on app/build.gradle
> +        targetCompatibility JavaVersion.VERSION_11
и тут зачем поменялась версия?

2023-10-31 10:22 UTC, onreg commented on build.gradle
> +        kotlin_version = '1.7.1'
Почему понизил версию котлина?

2023-10-31 10:22 UTC, onreg commented on build.gradle
> +        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0-RC2'
что это за плагин classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0-RC2', где его используешь?

2023-10-31 10:22 UTC, onreg commented on app/src/main/java/com/example/tmdb/data/model/utils/TypeConverter.kt
> +        }
```
MOVIES_TYPE
SERIES_TYPE
```

От этих констант можно избавитсья используя имя енама

2023-10-31 10:22 UTC, onreg commented on app/src/main/java/com/example/tmdb/ui/home/MovieOverviewViewModel.kt
> +    savedStateHandle: SavedStateHandle
Это не очень хороший вариант, сделай что бы тут был сразу `Movie`

2023-11-01 11:59 UTC, onreg requested changes

2023-11-01 11:59 UTC, onreg commented on app/src/main/java/com/example/tmdb/ui/home/MovieOverviewFragment.kt
> +    private lateinit var binding: FragmentMovieItemOverviewBinding
binding нужно занулять, когда вьюшка уничтожается 
https://developer.android.com/topic/libraries/view-binding#fragments

2023-11-03 14:13 UTC, onreg approved these changes

2023-11-03 14:17 UTC, merged